# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation
---
PARALLEL: true
DEFAULT_BRANCH: main
SHOW_ELAPSED_TIME: true
CLEAR_REPORT_FOLDER: true
OUTPUT_DETAIL: detailed
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: false
JSON_REPORTER: true
JSON_REPORTER_OUTPUT_DETAIL: simple
SARIF_REPORTER: true
FILEIO_REPORTER: false
FORMATTERS_DISABLE_ERRORS: false
JAVASCRIPT_DEFAULT_STYLE: prettier
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - SPELL_LYCHEE
  - REPOSITORY_GITLEAKS
  - ENV_DOTENV_LINTER
  - YAML_YAMLLINT
  - JSON_JSONLINT
  - ACTION_ACTIONLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
EXCLUDED_DIRECTORIES:
  - '.git'
  - 'node_modules'
  - '.dev'
FILTER_REGEX_EXCLUDE: (.git/|node_modules/|.dev/|.*-megalinter_*\.txt|.*\.drawio|.*\.mmd|.*\.svg|.*\.SVG)
MARKDOWN_MARKDOWNLINT_ARGUMENTS: --disable MD025
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml
MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: --quiet
REPOSITORY_GITLEAKS_CONFIG_FILE: .gitleaks.toml
REPOSITORY_GITLEAKS_ARGUMENTS: --redact
ENV_DOTENV_LINTER_FILE_EXTENSIONS: ['.env', '.env.*']
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml
# COPYPASTE_JSCPD_CONFIG_FILE: .jscpd.json
JSON_JSONLINT_CONFIG_FILE: .jsonlintrc.json
# ACTION_ACTIONLINT_CONFIG_FILE: .actionlint.yml
ACTION_ACTIONLINT_ARGUMENTS: -shellcheck
LINTER_RULES_PATH: .github/linters
SPELL_LYCHEE_CONFIG_FILE: .lychee.toml
# LOG_LEVEL: DEBUG
