resources:
  repositories:
  - name: microsoft/symphony
    type: github
    repository: symphony
    ref: enpolat/azure-devops-ci-bicep
    endpoint: Symphony2

name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  - none

pr:
  - none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Validate
    displayName: "Validate"
    steps:
      - checkout: symphony
