resources:
  repositories:
  - repository: symphony
    name: microsoft/symphony
    type: github
    ref: enpolat/azure-devops-ci-bicep
    endpoint: Symphony2

name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  - none

pr:
  - none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Validate
    displayName: "Validate"
    steps:
      - checkout: symphony

      - task: Bash@3
        displayName: "Install Azure CLI"
        inputs:
          filePath: 'orchestrators/scripts/setup-azcli.sh'
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          bashEnvValue: '~/.profile'
          failOnStderr: true

      - task: Bash@3
        displayName: "Install gitleaks"
        inputs:
          filePath: 'orchestrators/scripts/setup-gitleaks.sh'
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          bashEnvValue: '~/.profile'
          failOnStderr: true

      - task: Bash@3
        displayName: "Run gitleaks"
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          targetType: 'inline'
          script: | 
            echo 'create ./results directory'
            mkdir results

            source ./scanners.sh
            run_gitleaks './../../IAC/Terraform' './results/gitleaks-report' 'json' 'info' 

      - task: Bash@3
        displayName: "Run linter"
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          targetType: 'inline'
          script: |
            source ./iac.bicep.sh
            pushd .
            cd ./../../IAC/Bicep/bicep
            modules=$(find . -type f -name '*.bicep' | sort -u)

            SAVEIFS=$IFS
            IFS=$'\n'
            array=($modules)
            IFS=$SAVEIFS
            len=${#array[@]}
            for deployment in "${array[@]}"
              do
                echo "linting ${deployment}"
                pushd .
                cd $deployment
                lint
                code=$?
                if [[ $code != 0 ]]; then
                  echo "bicep linting failed- returned code ${code}"
                  exit $code
                fi
                popd
                echo "------------------------"
              done
            popd
