jobs:
  - job: Preview
    displayName: "Preview"
    dependsOn:
      - Validate

    steps:
      - checkout: symphony

      - task: Bash@3
        displayName: "Install Azure CLI"
        inputs:
          filePath: 'orchestrators/scripts/setup-azcli.sh'
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          bashEnvValue: '~/.profile'
          failOnStderr: true

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'Symphony-kv2'
          KeyVaultName: 'kv-symphony-env'
          SecretsFilter: '*'
          RunAsPreJob: true

      - task: Bash@3
        displayName: "Run bicep preview"
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          targetType: 'inline'
          script: |
            source ./iac.bicep.sh

            azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'

            ENVIRONMENT=$(cat /env/bicep/dev/parameters.json | jq -r '.parameters.environment.value')
            LOCATION=$(cat /env/bicep/dev/parameters.json | jq -r '.parameters.location.value')
            RESOURCE_GROUP_NAME="symphony-bicep-preview-${ENVIRONMENT}"

            WORKSPACE_PATH="$(System.DefaultWorkingDirectory)" \
            RUN_ID="$(Build.BuildId)" \
            ENVIRONMENT="${ENVIRONMENT}" \
            LOCATION="${LOCATION}" \
            RESOURCE_GROUP_NAME="${RESOURCE_GROUP_NAME}" \
            ./iac.bicep.preview.azdo.sh
