resources:
  repositories:
  - repository: symphony
    name: microsoft/symphony
    type: github
    ref: main
    endpoint: Symphony2

name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  - none

pr:
  - none

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: EnvironmentName
    value: "dev"
  - name : KeyVaultAzureSubscriptionName
    value: "Symphony-kv2"
  - name : KeyVaultName
    value: "kv-symphony-env"

jobs:
  - template: ./ci_bicep_job0_validate.yml
    parameters:
      EnvironmentName: $(EnvironmentName)
      KeyVaultAzureSubscriptionName: $(KeyVaultAzureSubscriptionName)
      KeyVaultName: $(KeyVaultName)
  - template: ./ci_bicep_job1_preview-deploy.yml
    parameters:
      EnvironmentName: $(EnvironmentName)
      KeyVaultAzureSubscriptionName: $(KeyVaultAzureSubscriptionName)
      KeyVaultName: $(KeyVaultName)
  - template: ./ci_bicep_job2_e2etest.yml
    parameters:
      EnvironmentName: $(EnvironmentName)
      KeyVaultAzureSubscriptionName: $(KeyVaultAzureSubscriptionName)
      KeyVaultName: $(KeyVaultName)
