resources:
  repositories:
  - repository: symphony
    name: microsoft/symphony
    type: github
    ref: enpolat/bicep-pipeline-e2e-test-job
    endpoint: Symphony2

name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  - none

pr:
  - none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - template: ./ci_bicep_job0_validate.yml
  - template: ./ci_bicep_job1_preview.yml
  - template: ./ci_bicep_job2_deploy.yml
  - template: ./ci_bicep_job3_e2etest.yml
