jobs:
  - job: e2etest
    displayName: "e2e Test"
    workspace:
      clean:  resources

    steps:
      - checkout: symphony

      - task: Bash@3
        displayName: "Install Azure CLI"
        inputs:
          filePath: 'orchestrators/scripts/setup-azcli.sh'
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          bashEnvValue: '~/.profile'
          failOnStderr: true

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'Symphony-kv2'
          KeyVaultName: 'kv-symphony-env'
          SecretsFilter: '*'
          RunAsPreJob: true

      - task: Bash@3
        displayName: "Run end to end tests"
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          targetType: 'inline'
          script: |
            source ./tests.runner.sh
            azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'

            export resource_group_name=$(STATERG)
            export storage_account_name=$(STATESTORAGEACCOUNT) 
            export container_name=$(STATECONTAINER)

            bicep
