jobs:
  - job: Preview
    displayName: "Preview"

    steps:
      - checkout: symphony

      - task: Bash@3
        displayName: "Install Azure CLI"
        inputs:
          filePath: 'orchestrators/scripts/setup-azcli.sh'
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          bashEnvValue: '~/.profile'
          failOnStderr: true

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'Symphony-kv2'
          KeyVaultName: 'kv-symphony-env'
          SecretsFilter: '*'
          RunAsPreJob: true

      - task: Bash@3
        displayName: "Run bicep preview"
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          targetType: 'inline'
          script: |
            source ./iac.bicep.sh
            azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'
            pushd .
            cd ./../../IAC/Bicep/bicep
            modules=$(find . -type f -name 'main.bicep' | sort -u)
            SAVEIFS=$IFS
            IFS=$'\n'
            array=(${modules})
            IFS=$SAVEIFS
            len=${#array[@]}
            for deployment in "${array[@]}"
              do
                pushd .
                path=$(dirname "${deployment}")
                fileName=$(basename "${deployment}")
                cd "${path}"
                echo "bicep preview ${path}/${fileName}"
                paramFiles="$(System.DefaultWorkingDirectory)/env/bicep/dev/parameters.json"
                preview "${fileName}" "${paramFiles}"
                code=$?
                if [[ $code != 0 ]]; then
                  echo "biceplint failed - returned code ${code}"
                  exit $code
                fi
                popd
                echo "------------------------"
              done
            popd
