jobs:
  - job: Deploy
    displayName: "Deploy"
    dependsOn:
      - Preview

    steps:
      - checkout: symphony

      - task: Bash@3
        displayName: "Install Azure CLI"
        inputs:
          filePath: 'orchestrators/scripts/setup-azcli.sh'
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          bashEnvValue: '~/.profile'
          failOnStderr: true

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'Symphony-kv2'
          KeyVaultName: 'kv-symphony-env'
          SecretsFilter: '*'
          RunAsPreJob: true

      - task: Bash@3
        displayName: "Run bicep validate"
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          targetType: 'inline'
          script: |
            source ./iac.bicep.sh

            azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'

            WORKSPACE_PATH="$(System.DefaultWorkingDirectory)" \
            RUN_ID="$(Build.BuildId)" \
            LOCATION="westus" \
            ENVIRONMENT="dev" \
            ./iac.bicep.deploy.azdo.sh
