name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  - none

pr:
  - none

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: workDir
    value: "$(System.DefaultWorkingDirectory)/IAC/Terraform/terraform"
  - name: runModuleTest
    value: true
  - name: runBackupState
    value: true

  #============================================================
  # The following Variables Should Be Set On the Pipeline
  #============================================================
  - name: env
    value: "dev"
  - name: KeyVaultSvcName
    value: "Symphony-KV"
  - name: KeyVaultName
    value: "kv-symphony-env"
  - name: goVersion
    value: "1.18.1"
  - name: terraformVersion
    value: "1.1.7"

stages:
  - stage: Validate
    displayName: "Validate Configuration"
    jobs:
      - template: ./ci_terraform_validate.yml
        parameters:
          goVersion: "$(goVersion)"
          terraformVersion: "$(terraformVersion)"
          KeyVaultSvcName: "$(KeyVaultSvcName)"
          KeyVaultName: "$(KeyVaultName)"

      - template: ./ci_terraform_previewdeploy.yml
        parameters:
          goVersion: "$(goVersion)"
          terraformVersion: "$(terraformVersion)"
          KeyVaultSvcName: "$(KeyVaultSvcName)"
          KeyVaultName: "$(KeyVaultName)"

      - template: ./ci_terraform_test.yml
        parameters:
          goVersion: "$(goVersion)"
          terraformVersion: "$(terraformVersion)"
          KeyVaultSvcName: "$(KeyVaultSvcName)"
          KeyVaultName: "$(KeyVaultName)"

      - template: ./ci_terraform_report.yml
        parameters:
          KeyVaultSvcName: "$(KeyVaultSvcName)"
          KeyVaultName: "$(KeyVaultName)"
