
resources:
  repositories:
  - repository: Symphony
    type: github
    endpoint: Symphony2
    name: microsoft/symphony
    ref: add_azdo_ci_tf #main

name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  - none

pr:
  - none

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: workDir
    value: "$(System.DefaultWorkingDirectory)/IAC/Terraform//terraform"
  - name: runModuleTest
    value: true
  - name: runBackupState
    value: true


#============================================================
# The following Variables Should Be Set On the Pipeline
#============================================================
  - name: env
    value: "dev"

stages:
 - stage: Validate
   displayName: "Validate Configuration"
   jobs:
     - template: ./ci_terraform_validate.yml
     
     - template: ./ci_terraform_preview.yml
     
     - template: ./ci_terraform_test.yml

     - template: ./ci_terraform_report.yml 