
resources:
  repositories:
  - repository: Symphony
    type: github
    endpoint: Symphony2
    name: microsoft/symphony
    ref: main

name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  - none

pr:
  - none

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: workDir
    value: "$(System.DefaultWorkingDirectory)/IAC/Terraform//terraform"
  - name: runModuleTest
    value: true
  - name: runBackupState
    value: true


#============================================================
# The following Variables Should Be Set On the Pipeline
#============================================================
  - name: env
    value: "dev"
  - name : envKVSVCName
    value: "Symphony-kv2"
  - name : envKVName
    value: "kv-symphony-env"
  - name: goVersion
    value: "1.18.1"
  - name: terraformVersion
    value: "1.1.7"
  
stages:
 - stage: Validate
   displayName: "Validate Configuration"
   jobs:
     - template: ./ci_terraform_validate.yml
       parameters:
          goVersion : "$(goVersion)"
          terraformVersion: "$(terraformVersion)"
          envKVSVCName: "$(envKVSVCName)"
          envKVName: "$(envKVName)"

     - template: ./ci_terraform_preview.yml
       parameters:
          goVersion : "$(goVersion)"
          terraformVersion: "$(terraformVersion)"
          envKVSVCName: "$(envKVSVCName)"
          envKVName: "$(envKVName)"

     - template: ./ci_terraform_test.yml
       parameters:
          goVersion : "$(goVersion)"
          terraformVersion: "$(terraformVersion)"
          envKVSVCName: "$(envKVSVCName)"
          envKVName: "$(envKVName)"

     - template: ./ci_terraform_report.yml
       parameters:
          envKVSVCName: "$(envKVSVCName)"
          envKVName: "$(envKVName)"