
resources:
  repositories:
  - repository: Symphony
    type: github
    endpoint: Symphony2
    name: microsoft/symphony
    ref: add_azdo_ci_tf #main

name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  - none

pr:
  - none

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: env
    value: "dev"
  - name: workDir
    value: "$(System.DefaultWorkingDirectory)/IAC/Terraform//terraform"
  - name: runCredScan
    value: true
  - name: runTfValidation
    value: true
  - name: runTfLint
    value: true
  - name: runTfPlan
    value: true
  - name: runTfDestroy
    value: true
  - name: runTfApply
    value: true
  - name: runUnitTest
    value: true
  - name: runIntegrationTest
    value: true
  - name: TfPlanPipelineFolderPath
    value: "\\infrastructure\\shared"
  - name: TfApplyPipelineFolderPath
    value: "\\infrastructure\\shared"
  - name: TfPlanPipelineName
    value: "tfplan"
  - name: TfApplyPipelineName
    value: "tfapply"


stages:
 - stage: Validate
   displayName: "Validate Configuration"
   jobs:
      # Validate and Initialize Layers #
      - job: TfValidation
        workspace:
          clean:  resources       
        displayName: "Validate"
        #variables:
          #deployments: $[ dependencies.gitDiff.outputs['gitDiff.DEPLOYMENTS'] ]
        steps:
          - checkout: Symphony 
          
          - task: Bash@3
            displayName: "Install Terraform"
            inputs:
              filePath: 'orchestrators/scripts/setup-terraform.sh'
              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
              bashEnvValue: '~/.profile'
              failOnStderr: true
          
          - task: Bash@3
            displayName: "Install Tflint"
            inputs:
              filePath: 'orchestrators/scripts/setup-tflint.sh'
              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
              bashEnvValue: '~/.profile'
              failOnStderr: true

          - task: Bash@3
            displayName: "Install gitleaks"
            inputs:
              filePath: 'orchestrators/scripts/setup-gitleaks.sh'
              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
              bashEnvValue: '~/.profile'
              failOnStderr: true

          # orchestrators\scripts\setup-tflint.sh

          #- task: Bash@3
          #  displayName: "Install Go"
          #  inputs:
          #    filePath: 'orchestrators/scripts/setup-go.sh'
          #    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
          #    bashEnvValue: '~/.profile'
          #    failOnStderr: true
          
          - task: Bash@3
            displayName: "Run gitleaks"
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
              targetType: 'inline'
              script: | 
                echo 'create ./results directory'
                mkdir results

                source ./scanners.sh
                run_gitleaks './../../IAC/Terraform' './results/gitleaks-report' 'json' 'info' 

          - task: Bash@3
            displayName: "Run Terraform lint"
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
              targetType: 'inline'
              script: | 
                echo 'Run tflint'

                

                source ./iac.tf.sh

                pushd .

                cd ./../../IAC/Terraform/terraform
                modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
                

                SAVEIFS=$IFS
                IFS=$'\n'

                array=($modules)
                IFS=$SAVEIFS

                len=${#array[@]}

                for deployment in "${array[@]}"
                        do
                          echo "START linting ${deployment}"

                          lint 
                          #if [[ "$(tflint "$(workDir)/${deployment}" | wc -l)" -gt 0 ]]; then
                          #  filePath=$(echo "${deployment}.xml" | sed -e 's/\//-/g')
                          #  tflint "$(workDir)/$deployment" > "$filePath"
                          #  echo "##vso[task.addattachment type=Distributedtask.Core.Summary;name=TFLint-$filePath-Results;]$(pwd)/$filePath"
                          #  echo "##vso[task.logissue type=error]${deployment} failed tflint scan."
                          #  exitcode=1
                          #else
                          #  echo "TFLint passed."
                          #fi
                          #echo "END linting ${deployment}"

                        done

                popd
                
                
                 

              