# yaml-language-server: $schema=https://json.schemastore.org/prettierrc.json
---
printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: 'consistent'
jsxSingleQuote: true
trailingComma: 'none'
bracketSpacing: true
bracketSameLine: false
endOfLine: 'lf'
embeddedLanguageFormatting: 'auto'
arrowParens: 'always'
htmlWhitespaceSensitivity: 'css'
vueIndentScriptAndStyle: true
