parameters:
  - name: goVersion
    type: string
  - name: terraformVersion
    type: string
  - name: keyVaultArmSvcConnectionName
    type: string
  - name: keyVaultName
    type: string

jobs:
  - job: Test
    workspace:
      clean: resources
    displayName: "E2E Test"
    dependsOn: PreviewDeploy

    steps:
      - checkout: self

      - task: Bash@3
        displayName: "Install Terraform"
        inputs:
          filePath: "scripts/orchestrators/setup-terraform.sh"
          workingDirectory: "$(System.DefaultWorkingDirectory)/scripts/orchestrators"
          arguments: ${{ parameters.terraformVersion }}
          bashEnvValue: "~/.profile"
          failOnStderr: true

      - task: GoTool@0
        inputs:
          version: ${{ parameters.goVersion }}
          goBin: "$(System.DefaultWorkingDirectory)"

      - script: echo '##vso[task.prependpath]$(System.DefaultWorkingDirectory)'

      - task: AzureKeyVault@2
        displayName: "Pull env cred from Azure Key vault"
        inputs:
          azureSubscription: ${{ parameters.keyVaultArmSvcConnectionName }}
          keyVaultName: ${{ parameters.keyVaultName }}
          secretsFilter: "*"
          runAsPreJob: true

      - task: Bash@3
        displayName: "Run E2E tests"
        env:
          WORKSPACE_PATH: $(System.DefaultWorkingDirectory)
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_TENANT_ID: $(tenantId)
          ARM_CLIENT_ID: $(clientId)
          ARM_CLIENT_SECRET: $(clientSecret)
          STATE_RG: $(stateRg)
          STATE_STORAGE_ACCOUNT: $(stateStorageAccount)
          STATE_CONTAINER: $(stateContainer)
          ENVIRONMENT_NAME: $(environmentName)
          TEST_TAG: ''
        inputs:
          workingDirectory: "$(System.DefaultWorkingDirectory)/scripts/orchestrators"
          targetType: "filePath"
          filePath: "scripts/orchestrators/iac.tf.test.sh"

      - task: PublishTestResults@2
        displayName: "Publish E2E test results"
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "*.xml"
          searchFolder: "$(System.DefaultWorkingDirectory)/IAC/Terraform/test/terraform"
          failTaskOnFailedTests: true
          testRunTitle: "E2E Test"
          publishRunAttachments: true
          mergeTestResults: true
