parameters:
  - name: pipelineName
    type: string
  - name: eventName
    type: string
  - name: eventGroupId
    type: string
  - name: data
    type: string
  - name: keyVaultArmSvcConnectionName
    type: string
  - name: keyVaultName
    type: string
  - name: comment
    type: string
  - name: dependsOn
    type: object
    default: []

jobs:
  - job: StoreEvent
    displayName: "Store Event: ${{ parameters.eventName }}"
    dependsOn: ${{ parameters.dependsOn }}
    variables:
      data: ${{ parameters.data }}
      eventGroupId: ${{ parameters.eventGroupId }}
      comment: ${{ parameters.comment }}
    
    steps:
      - checkout: self

      - task: Bash@3
        displayName: "Install Azure CLI"
        inputs:
          filePath: "scripts/orchestrators/setup-azcli.sh"
          workingDirectory: "$(System.DefaultWorkingDirectory)/scripts/orchestrators"
          bashEnvValue: "~/.profile"
          failOnStderr: true

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: ${{ parameters.keyVaultArmSvcConnectionName }}
          keyVaultName: ${{ parameters.keyVaultName }}
          secretsFilter: "*"
          runAsPreJob: true

      - task: Bash@3
        name: StoreEvent
        displayName: "Store Event"
        env:
          WORKSPACE_PATH: $(System.DefaultWorkingDirectory)
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_TENANT_ID: $(tenantId)
          ARM_CLIENT_ID: $(clientId)
          ARM_CLIENT_SECRET: $(clientSecret)
          EVENTS_STORAGE_ACCOUNT: $(eventsStorageAccount)
          EVENTS_TABLE_NAME: $(eventsTableName)
        inputs:
          workingDirectory: "$(System.DefaultWorkingDirectory)/scripts/orchestrators"
          targetType: "inline"
          failOnStderr: false
          script: |
            source ./events.sh

            echo "eventGroupId: $(eventGroupId)"
            echo "data: $(data)"

            store_event "${{ parameters.pipelineName }}" "${{ parameters.eventName }}" "$(eventGroupId)" "$(data)"

      - task: Bash@3
        name: CommentPR
        displayName: "Comment PR"
        env:
          System.AccessToken: $(System.AccessToken)
        inputs:
          targetType: "inline"
          failOnStderr: false
          script: |
            prId=$(System.PullRequest.PullRequestId)
            repoId=$(Build.Repository.Id)
            uri="$(System.TeamFoundationCollectionUri)_apis/git/repositories/$repoId/pullRequests/$prId/threads?api-version=6.0"

            echo "Commenting on PR $prId in repo $repoId"
            echo "URI: $uri"
            echo "Comment: $(comment)"

            body='{"comments": [{"parentCommentId": 0,"content": "'"$(comment)"'","commentType": 1}]}'
            echo $body
            curl -X POST -H "Content-Type: application/json" -d "$body" -u :$(System.AccessToken) $uri
