parameters:
  - name: pipelineName
    type: string
  - name: eventName
    type: string
  - name: eventGroupId
    type: string
  - name: data
    type: string
  - name: keyVaultArmSvcConnectionName
    type: string
  - name: keyVaultName
    type: string
  - name: comment
    type: string

jobs:
  - job: StoreEvent
    displayName: "Store Event"
    
    steps:
      - checkout: self

      - task: Bash@3
        displayName: "Install Azure CLI"
        inputs:
          filePath: "scripts/orchestrators/setup-azcli.sh"
          workingDirectory: "$(System.DefaultWorkingDirectory)/scripts/orchestrators"
          bashEnvValue: "~/.profile"
          failOnStderr: true

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: ${{ parameters.keyVaultArmSvcConnectionName }}
          keyVaultName: ${{ parameters.keyVaultName }}
          secretsFilter: "*"
          runAsPreJob: true

      - task: Bash@3
        name: StoreEvent
        displayName: "Store Event"
        env:
          WORKSPACE_PATH: $(System.DefaultWorkingDirectory)
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_TENANT_ID: $(tenantId)
          ARM_CLIENT_ID: $(clientId)
          ARM_CLIENT_SECRET: $(clientSecret)
          EVENTS_STORAGE_ACCOUNT: $(eventsStorageAccount)
          EVENTS_TABLE_NAME: $(eventsTableName)
        inputs:
          workingDirectory: "$(System.DefaultWorkingDirectory)/scripts/orchestrators"
          targetType: "inline"
          failOnStderr: true
          script: |
            source ./events.sh

            store_event "$(parameters.pipelineName)" "$(parameters.eventName)" "$(parameters.eventGroupId)" "$(parameters.data)"

      - task: Bash@3
        name: CommentPR
        displayName: "Comment PR"
        env:
          System.AccessToken: $(System.AccessToken)
          comment: $(parameters.comment)
        inputs:
          targetType: "inline"
          failOnStderr: true
          script: |
            prId=$(System.PullRequest.PullRequestId)
            repoId=$(Build.Repository.Id)
            uri="$(System.TeamFoundationCollectionUri)_apis/git/repositories/$repoId/pullRequests/$prId/threads?api-version=6.0"
            body='{"comments": [{"parentCommentId": 0,"content": "'"$comment"'","commentType": 1}]}'
            curl -X POST -H "Content-Type: application/json" -d "$body" -u :$(System.AccessToken) $uri
