name: Validate

on:
  workflow_call:

jobs:
  Validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Toolset
        run: |
          ./setup-azcli.sh
          ./setup-gitleaks.sh
          ./setup-powershell.sh
          ./setup-pester.sh
          ./setup-armttk.sh
          ./setup-shellspec.sh
        working-directory: orchestrators/scripts

      - name: Run Gitleaks
        run: |
            source ./scanners.sh
            run_gitleaks './../../IAC/Bicep' './' 'json' 'info' 
        working-directory: orchestrators/scripts