---
name: "Template-Store-Event"

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      pipelineName:
        type: string
        required: true
      eventName:
        type: string
        required: true
      eventGroupId:
        type: string
        required: true
      data:
        type: string
        required: true
      keyVaultName:
        type: string
        required: true
      comment:
        type: string
        required: false
    secrets:
      azureEnviromentCredentials:
        required: true

jobs:
  StoreEvent:
    name: Store Event
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/login@v1
        name: Run Azure Login
        with:
          creds: "${{ secrets.azureEnviromentCredentials }}"
          environment: "AzureCloud"

      - name: Get KeyVault Secret(s)
        id: LoadSecrets
        env:
          SECRETS: "clientId, clientSecret, subscriptionId, tenantId, eventsStorageAccount, eventsTableName"
          KEY_VAULT_NAME: ${{ inputs.keyVaultName }}
        run: ./github.loadsecrets.sh
        working-directory: scripts/orchestrators

      - name: Store Event
        env:
          WORKSPACE_PATH: ${{ github.workspace }}
        run: |
          export ARM_TENANT_ID=${{ steps.LoadSecrets.outputs.tenantId }}
          export ARM_SUBSCRIPTION_ID=${{ steps.LoadSecrets.outputs.subscriptionId }}
          export ARM_CLIENT_ID=${{ steps.LoadSecrets.outputs.clientId }}
          export ARM_CLIENT_SECRET=${{ steps.LoadSecrets.outputs.clientSecret }}
          export EVENTS_STORAGE_ACCOUNT=${{ steps.LoadSecrets.outputs.eventsStorageAccount }}
          export EVENTS_TABLE_NAME=${{ steps.LoadSecrets.outputs.eventsTableName }}

          source ./events.sh

          store_event "${{ inputs.pipelineName }}" "${{ inputs.eventName }}" "${{ inputs.eventGroupId }}" "${{ inputs.data }}"

        working-directory: scripts/orchestrators

      - name: Comment PR
        if: ${{ inputs.comment != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ inputs.comment }}`
            });
