---
name: "Template-Query-Event"

on: # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      events:
        description: "Json array with events"
        value: ${{ jobs.QueryEvent.outputs.events}}
    inputs:
      pipelineName:
        type: string
        required: true
      eventName:
        type: string
        required: true
      eventGroupId:
        type: string
        required: true
      keyVaultName:
        type: string
        required: true

jobs:
  QueryEvent:
    name: Query Events
    runs-on: ubuntu-latest
    outputs:
      events: ${{ steps.QueryEvents.outputs.events }}
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/login@v1
        name: Run Azure Login
        with:
          environment: "AzureCloud"

      - name: Get KeyVault Secret(s)
        id: LoadSecrets
        env:
          SECRETS: "eventsStorageAccount, eventsTableName"
          KEY_VAULT_NAME: ${{ inputs.keyVaultName }}
        run: ./github.loadsecrets.sh
        working-directory: scripts/orchestrators

      - name: Query Events
        id: QueryEvents
        env:
          WORKSPACE_PATH: ${{ github.workspace }}
        run: |
          export EVENTS_STORAGE_ACCOUNT=${{ steps.LoadSecrets.outputs.eventsStorageAccount }}
          export EVENTS_TABLE_NAME=${{ steps.LoadSecrets.outputs.eventsTableName }}

          source ./events.sh

          events=$(query_events "${{ inputs.pipelineName }}" "${{ inputs.eventName }}" "${{ inputs.eventGroupId }}")
          echo "events=$events" >> $GITHUB_OUTPUT

        working-directory: scripts/orchestrators
