name: "Spike"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  Spike:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - name: Run script
        run: |
          printenv
