---
name: "Cleanup Bicep"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: "Pull Request Number"
        required: true
      tenantId:
        description: "Target tenant id (if overriding default)"
        required: false
      subscriptionId:
        description: "Target subscription (if overriding default)"
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  Destroy:
    uses: ./.github/workflows/template.bicep.cleanup.yml
    with:
      pullRequestnumber: ${{ github.event.inputs.pullRequestNumber }}
      githubEnvironment: symphony
      tenantId: ${{ github.event.inputs.tenantId }}
      subscriptionId: ${{ github.event.inputs.subscriptionId }}
    secrets: inherit
