---
name: "Cleanup Bicep"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: "Pull Request Number"
        required: true
      keyVaultName:
        description: "Environment Key Vault Name"
        required: true
        default: "kv-ykiihqqa-195"

permissions:
  id-token: write
  contents: read

jobs:
  Destroy:
    uses: ./.github/workflows/template.bicep.cleanup.yml
    with:
      pullRequestnumber: ${{ github.event.inputs.pullRequestNumber }}
      keyVaultName: ${{ github.event.inputs.keyVaultName }}
      githubEnvironment: symphony
    secrets: inherit
